version: '3'
services:

  inventory-management:
    image: inventory-management
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
     - "4000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://db_223306781sit722week7_user:kL3shsfGhNLOYWSThOG05dwLfoW4NGpd@dpg-cr87jdlsvqrc73dqj9kg-a.oregon-postgres.render.com/db_223306781sit722week7
    restart: "no"

  book-catalog:
    image: book-catalog
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "4001:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://db_223306781sit722week7_user:kL3shsfGhNLOYWSThOG05dwLfoW4NGpd@dpg-cr87jdlsvqrc73dqj9kg-a.oregon-postgres.render.com/db_223306781sit722week7
    restart: "no"